### ISSUE TITLE
scale_and_crop: unorderable types: float() < str()

### ISSUE THREAD

**Issue by humatic** [sehmaschine/django-filebrowser#296]
When I try to "change" an image file in the admin, I get this error. I believe it's related to issue #278.

What I think happens is that either the `width` or the `height` are coming in as strings and causing Python  to choke on the comparison.

I can fix by adding these lines:

```
width = float(width or 0)
height = float(height or 0)
```

However, I have no idea how casting to a float affects the rest of the algorithm.

I'm using Python 3.4 with Filebrowser 3.6.1.

Thanks!

**Comment by sehmaschine** [comment]
did you run the tests?

**Comment by humatic** [comment]
Yes:

```
======================================================================
ERROR: runTest (filebrowser.tests.test_sites.TestSite_filebrowser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/tests/test_sites.py", line 442, in runTest
    test_do_upload(self)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/tests/test_sites.py", line 135, in test_do_upload
    data = json.loads(response.content)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_scale_crop (filebrowser.tests.test_versions.VersionTemplateTagsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/tests/test_versions.py", line 120, in test_scale_crop
    version = scale_and_crop(im, "", 375, "")
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/utils.py", line 70, in scale_and_crop
    if (x < width or not x) and (y < height or not y):
TypeError: unorderable types: float() < str()

======================================================================
ERROR: test_version (filebrowser.tests.test_versions.VersionTemplateTagsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/tests/test_versions.py", line 266, in test_version
    r = t.render(c)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/templatetags/fb_versions.py", line 48, in render
    version = fileobject.version_generate(version_suffix)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/base.py", line 506, in version_generate
    version_path = self._generate_version(version_suffix)
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/base.py", line 527, in _generate_version
    version = scale_and_crop(im, VERSIONS[version_suffix]['width'], VERSIONS[version_suffix]['height'], VERSIONS[version_suffix]['opts'])
  File "/home/rtaylor/Workspace/backbox/.venv/lib/python3.4/site-packages/filebrowser/utils.py", line 70, in scale_and_crop
    if (x < width or not x) and (y < height or not y):
TypeError: unorderable types: float() < str()

----------------------------------------------------------------------
Ran 40 tests in 1.111s

FAILED (errors=3)
```

**Comment by sehmaschine** [comment]
well, that should be solved with 3.6.2 (current master). can you give that a try?

**Comment by V1ce** [comment]
Hi,

I have the same error when i try to browse a folder (that contain an image) with django-filebrowser in ckeditor admin widget, so i allow myself to post here for dont duplicate.

Template error:
In template C:\Python34\lib\site-packages\django_filebrowser-3.6.2-py3.4.egg\filebrowser\templates\filebrowser\include\filelisting.html, error at line 77
   unorderable types: float() < str()

Thanks

**Comment by humatic** [comment]
@sehmaschine I downloaded master (3.6.2) and ran the tests. Same errors. I'm not sure what to make of it. It only seems to happen in my dev environment, using the Django builtin server. On my live server the error doesn't happen. Perhaps I've got a broken dependency somewhere..

**Comment by sehmaschine** [comment]
@humatic it should definitely work with 3.6.2 (I'm able to run all tests and we fixed this issue with #278).

**Comment by humatic** [comment]
For whatever weird reason, on my system the `height` variable is coming in as a string instead of an integer. Python then chokes on the comparison operator.

As I said, I've got it manually patched, so for now I'm content. Do as you will. :)

**Comment by sehmaschine** [comment]
@humatic sorry, you are right – there's been an error with python3. we have fixed that and added the tests (there's been another small issue with scale and crop). should work now with master.

**Comment by sehmaschine** [comment]
closing this for now since it's been fixed. please reopen if this issue still exists.
