### ISSUE TITLE
TypeError for NoneType value of FileBrowseField

### ISSUE THREAD

**Issue by petrikoz** [sehmaschine/django-filebrowser#337]
Environment:

* FileBrowser: 3.9.1
* Django: 1.11.5
* Grappelli: 2.10.1
* Python: 3.6.2

I have model with field:
```python
field_name = FileBrowseField('Field label', max_length=255, format='document', blank=True, null=True)
```

And when I save this field empty I have error:

```python
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1511, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1440, in _changeform_view
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 384, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 402, in _clean_fields
    value = field.clean(value)
  File "/django-filebrowser/filebrowser/fields.py", line 77, in clean
    file_extension = os.path.splitext(value)[1].lower()
  File "/usr/local/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I think it happens because method `clean` of FileBrowseField parent (`django.forms.CharField`) returns `NoneType` instead of `''`.

If replace row `if value == '':` to `if not value:` in file [filebrowser/fields.py](https://github.com/sehmaschine/django-filebrowser/blob/3.9.1/filebrowser/fields.py#L75) error will disappear.

**Comment by groundupnews** [comment]
I got the same error when saving in the Admin.

To fix it without modifying the Filebrowser code, I removed all null=True
options on the FileBrowser fields, and then made migrations, specifying
that the value for existing null Filebrowser fields should be set to "".
This ended up being quite a lot of work (I have FileBrowseField(s) all over
my project, not least because migrating from null to non-null for Postgres
fields is non-trivial and not handled automatically by Django's migration
system.

Nathan Geffen
GroundUp Editor
Tel: +27 (0) 21 788 9163
Website: http://www.groundup.org.za

**Comment by sehmaschine** [comment]
Just checked the docs and the attribute `null = True` is a mistake (sorry for that). The `FileBrowseField` is basically a `CharField` and using `null = True` does not make sense therefore. Will update the docs.

**Comment by petrikoz** [comment]
Ok. Thank you. Going to write migrations for all my models as @groundupnews suggested.

**Comment by sehmaschine** [comment]
Reopened because docs updates are important in order to avoid this issue.
