### ISSUE TITLE
emacs lock files

### ISSUE THREAD

**Issue by jdnrg** [sehmaschine/django-filebrowser#362]
Howdy,
emacs lock files cause the browser to crash

```

Variable | Value
-- | --
attr | ('date',)
attrgetter | <class 'operator.attrgetter'>
self | <filebrowser.base.FileListing object at 0x7f5cbe39d1d0>
seq | <FileObject: uploads/products/documents/#product_buckets.txt#>,  <FileObject: uploads/products/documents/.#product_buckets.txt>]
```

It appears the the date is not being read properly

```
Traceback (most recent call last):
  File "/mnt/c/Users/jdupont/Documents/GitHub/products/v/lib/python3.5/site-packages/Django-2.1.4.dev20181102150026-py3.5.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/c/Users/jdupont/Documents/GitHub/products/v/lib/python3.5/site-packages/Django-2.1.4.dev20181102150026-py3.5.egg/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/jdupont/Documents/GitHub/products/v/lib/python3.5/site-packages/Django-2.1.4.dev20181102150026-py3.5.egg/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/jdupont/Documents/GitHub/django-filebrowser/filebrowser/decorators.py", line 43, in decorator
    return function(request, *args, **kwargs)
  File "/mnt/c/Users/jdupont/Documents/GitHub/products/v/lib/python3.5/site-packages/Django-2.1.4.dev20181102150026-py3.5.egg/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/jdupont/Documents/GitHub/products/v/lib/python3.5/site-packages/Django-2.1.4.dev20181102150026-py3.5.egg/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/mnt/c/Users/jdupont/Documents/GitHub/django-filebrowser/filebrowser/sites.py", line 302, in browse
    listing = filelisting.files_listing_filtered()
  File "/mnt/c/Users/jdupont/Documents/GitHub/django-filebrowser/filebrowser/base.py", line 159, in files_listing_filtered
    listing = list(filter(self.filter_func, self.files_listing_total()))
  File "/mnt/c/Users/jdupont/Documents/GitHub/django-filebrowser/filebrowser/base.py", line 136, in files_listing_total
    files = self.sort_by_attr(files, self.sorting_by)
  File "/mnt/c/Users/jdupont/Documents/GitHub/django-filebrowser/filebrowser/base.py", line 83, in sort_by_attr
    return sorted(seq, key=attrgetter(*attr))
TypeError: unorderable types: NoneType() < float()
```

**Comment by sehmaschine** [comment]
@jdnrg happy to lock at a PR. I'm not using emcas, therefore I'm not able to resolve this.

**Comment by jdnrg** [comment]
Ok, 
https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html

```
The file lock is really a file, a symbolic link with a special name, stored in the same directory as the file you are editing. The name is constructed by prepending .# to the filename of the buffer. The target of the symbolic link will be of the form user@host.pid:boot, where user is replaced with the current username (from user-login-name), host with the name of the host where Emacs is running (from system-name), pid with Emacs's process id, and boot with the time since the last reboot. :boot is omitted if the boot time is unavailable. (On file systems that do not support symbolic links, a regular file is used instead, with contents of the form user@host.pid:boot.)
```

so `ln -s .#somefile user@host.pid`
or `ln -s .#xliff.go stefan@Defiant.57125` 

see https://www.reddit.com/r/emacs/comments/5sxejq/foo_locked_by_stefandefiant_pid_1234_s_q_p_what/

**Comment by sehmaschine** [comment]
Thanks. I leave this open for a couple of weeks. Again, happy to take a look at a pull request.

**Comment by jdnrg** [comment]
lets close this for now. habe auch keine Zeit.
