### ISSUE TITLE
FileBrowser is not compatible with Django 4?

### ISSUE THREAD

**Issue by MaxDragonheart** [sehmaschine/django-filebrowser#406]
Using FileBrowser 3.14.1 with Django 4.0.1 I've this issue:

```
poetry run python3 manage.py makemigrations


Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/maxdragonheart/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/maxdragonheart/DEV_FOLDER/MIO/NewMiosito/personal_website/kernel/models.py", line 4, in <module>
    from abstracts.models import TimeManager, ModelPost
  File "/home/maxdragonheart/DEV_FOLDER/MIO/NewMiosito/personal_website/abstracts/models.py", line 7, in <module>
    from filebrowser.fields import FileBrowseField
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/filebrowser/fields.py", line 14, in <module>
    from filebrowser.sites import site
  File "/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/filebrowser/sites.py", line 18, in <module>
    from django.utils.translation import ugettext as _
ImportError: cannot import name 'ugettext' from 'django.utils.translation' (/home/maxdragonheart/.cache/pypoetry/virtualenvs/personal-site-bvVCchcE-py3.8/lib/python3.8/site-packages/django/utils/translation/__init__.py)
```

With downgrade to Django 3.2.6 the problem is solved.
I don't use `ugettext` but this:

    from django.utils.translation import gettext_lazy as _

**Comment by sehmaschine** [comment]
no, it isn't compatible yet (see versions with the docs). working on compatibility with Django 4.

**Comment by MaxDragonheart** [comment]
Ok, thank you :)
